// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIRequest(arg1, arg2, arg3, arg4) {
  return ObfuscatedCall(0, [arg1, arg2, arg3, arg4]);
}

export function CheckAndUpdateMods(arg1, arg2) {
  return ObfuscatedCall(1, [arg1, arg2]);
}

export function CheckClientInstalled(arg1, arg2) {
  return ObfuscatedCall(2, [arg1, arg2]);
}

export function CheckQMLauncherDirExists() {
  return ObfuscatedCall(3, []);
}

export function DownloadMod(arg1, arg2) {
  return ObfuscatedCall(4, [arg1, arg2]);
}

export function GetAppVersion() {
  return ObfuscatedCall(5, []);
}

export function GetEmbeddedServers() {
  return ObfuscatedCall(6, []);
}

export function GetHWID() {
  return ObfuscatedCall(7, []);
}

export function GetJavaPath(arg1) {
  return ObfuscatedCall(8, [arg1]);
}

export function GetLauncherDbConfig(arg1) {
  return ObfuscatedCall(9, [arg1]);
}

export function GetPlatform() {
  return ObfuscatedCall(10, []);
}

export function GetScreenResolutions() {
  return ObfuscatedCall(11, []);
}

export function GetServerMods(arg1, arg2) {
  return ObfuscatedCall(12, [arg1, arg2]);
}

export function GetSettings() {
  return ObfuscatedCall(13, []);
}

export function HasEmbeddedConfig() {
  return ObfuscatedCall(14, []);
}

export function InstallJava(arg1, arg2, arg3) {
  return ObfuscatedCall(15, [arg1, arg2, arg3]);
}

export function SaveSettings(arg1) {
  return ObfuscatedCall(16, [arg1]);
}

export function UninstallMinecraft(arg1) {
  return ObfuscatedCall(17, [arg1]);
}

export function ValidateJavaPath(arg1) {
  return ObfuscatedCall(18, [arg1]);
}

export function WindowClose() {
  return ObfuscatedCall(19, []);
}

export function WindowIsMaximized() {
  return ObfuscatedCall(20, []);
}

export function WindowMaximize() {
  return ObfuscatedCall(21, []);
}

export function WindowMinimize() {
  return ObfuscatedCall(22, []);
}
