// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function APIRequest(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<Record<string, any>>;

export function CheckAndUpdateMods(arg1:number,arg2:string):Promise<main.ModsUpdateResult>;

export function CheckClientInstalled(arg1:number,arg2:string):Promise<main.ClientCheckResult>;

export function CheckQMLauncherDirExists():Promise<boolean>;

export function DownloadMod(arg1:string,arg2:string):Promise<main.DownloadResult>;

export function GetAppVersion():Promise<string>;

export function GetEmbeddedServers():Promise<Array<main.EmbeddedServer>>;

export function GetHWID():Promise<string>;

export function GetJavaPath(arg1:string):Promise<string>;

export function GetLauncherDbConfig(arg1:number):Promise<main.LauncherDbConfig>;

export function GetPlatform():Promise<string>;

export function GetScreenResolutions():Promise<Array<string>>;

export function GetServerMods(arg1:number,arg2:string):Promise<main.ServerModsResult>;

export function GetSettings():Promise<main.Settings>;

export function HasEmbeddedConfig():Promise<boolean>;

export function InstallJava(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function UninstallMinecraft(arg1:number):Promise<main.UninstallResult>;

export function ValidateJavaPath(arg1:string):Promise<main.JavaValidationResult>;

export function WindowClose():Promise<void>;

export function WindowIsMaximized():Promise<boolean>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;
