// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {launcher} from '../models';

export function ApplyLauncherUpdate():Promise<string>;

export function CheckLauncherUpdateAvailable():Promise<boolean>;

export function CreateCloudGameAccount(arg1:string,arg2:string):Promise<string>;

export function CreateInstance(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CreateLocalAccount(arg1:string,arg2:string):Promise<string>;

export function DeleteCloudGameAccount(arg1:number):Promise<string>;

export function DeleteInstance(arg1:string):Promise<string>;

export function DeleteInstanceMod(arg1:string,arg2:string):Promise<string>;

export function DeleteInstanceResource(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteLocalAccount(arg1:string):Promise<string>;

export function DownloadRemoteStoreProject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function EnsureInstanceForServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<string>;

export function GetAccounts():Promise<Array<main.AccountInfo>>;

export function GetCatalogStoreSettings():Promise<main.CatalogStoreSettings>;

export function GetCloudElyLinked():Promise<boolean>;

export function GetCloudGameAccounts():Promise<Array<main.CloudGameAccountInfo>|string>;

export function GetCloudProfile():Promise<Record<string, any>>;

export function GetCreateInstanceLoaderVersions(arg1:string,arg2:string):Promise<Array<string>>;

export function GetCreateInstanceMinecraftVersions():Promise<Array<string>>;

export function GetCurrentAccount():Promise<Record<string, any>>;

export function GetCurseForgeKeySettings():Promise<main.CurseForgeKeySettings>;

export function GetGameAccountInventory(arg1:number):Promise<main.GameAccountInventoryResponse>;

export function GetInstanceDetails(arg1:string):Promise<main.InstanceDetails>;

export function GetInstances():Promise<Array<launcher.Instance>>;

export function GetLang():Promise<string>;

export function GetLauncherDebug():Promise<boolean>;

export function GetLauncherAPITarget():Promise<main.LauncherAPITargetSettings>;

export function GetLauncherAboutInfo():Promise<main.LauncherAboutInfo>;

export function GetLauncherVersion():Promise<string>;

export function GetMicrosoftAuthAvailable():Promise<boolean>;

export function GetNews():Promise<Array<main.NewsItem>>;

export function GetQMServerAPIBase():Promise<string>;

export function GetQMServersError():Promise<string>;

export function InvalidateQMServersCache():Promise<void>;

export function GetRecentServers():Promise<Array<main.ServerInfo>>;

export function GetSkinProviderConfig():Promise<Record<string, boolean>>;

export function HasCurseForgeAPIKey():Promise<boolean>;

export function LaunchInstance(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<string>;

export function LaunchInstanceWithAccount(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;

export function LoginAccount(arg1:boolean):Promise<string>;

export function LogoutAccount():Promise<string>;

export function LogoutCloudAccount(arg1:string):Promise<string>;

export function OpenBrowserForMicrosoft():Promise<string>;

export function OpenBrowserForQMServerCloud():Promise<string>;

export function OpenBrowserURL(arg1:string):Promise<string>;

export function OpenPath(arg1:string):Promise<string>;

export function ResolveInstanceResourceStoreLinks(arg1:string,arg2:string,arg3:string):Promise<main.ResourceStoreLinks>;

export function SearchRemoteStore(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<main.RemoteStoreSearchResponse>;

export function SetCatalogStoreSettings(arg1:boolean,arg2:boolean):Promise<string>;

export function SetCurseForgeSettingsKey(arg1:string,arg2:boolean,arg3:boolean):Promise<string>;

export function SetDefaultAccount(arg1:string):Promise<string>;

export function SetInstanceMemory(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SetInstanceModEnabled(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SetInstanceResourceEnabled(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function SetLang(arg1:string):Promise<void>;

export function SetLauncherDebug(arg1:boolean):Promise<string>;

export function SetLauncherAPITarget(arg1:boolean,arg2:string):Promise<string>;

export function SyncLocalAccountToCloud(arg1:string,arg2:string):Promise<string>;

export function SyncMicrosoftAccountToCloud():Promise<string>;

export function Translate(arg1:string):Promise<string>;

export function UpdateCloudGameAccount(arg1:number,arg2:string,arg3:string):Promise<string>;
