// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyLauncherUpdate() {
  return window['go']['main']['App']['ApplyLauncherUpdate']();
}

export function CheckLauncherUpdateAvailable() {
  return window['go']['main']['App']['CheckLauncherUpdateAvailable']();
}

export function CreateCloudGameAccount(arg1, arg2) {
  return window['go']['main']['App']['CreateCloudGameAccount'](arg1, arg2);
}

export function CreateInstance(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateInstance'](arg1, arg2, arg3, arg4);
}

export function CreateLocalAccount(arg1, arg2) {
  return window['go']['main']['App']['CreateLocalAccount'](arg1, arg2);
}

export function DeleteCloudGameAccount(arg1) {
  return window['go']['main']['App']['DeleteCloudGameAccount'](arg1);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function DeleteInstanceMod(arg1, arg2) {
  return window['go']['main']['App']['DeleteInstanceMod'](arg1, arg2);
}

export function DeleteInstanceResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteInstanceResource'](arg1, arg2, arg3);
}

export function DeleteLocalAccount(arg1) {
  return window['go']['main']['App']['DeleteLocalAccount'](arg1);
}

export function DownloadRemoteStoreProject(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['DownloadRemoteStoreProject'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function EnsureInstanceForServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['EnsureInstanceForServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetCatalogStoreSettings() {
  return window['go']['main']['App']['GetCatalogStoreSettings']();
}

export function GetCloudElyLinked() {
  return window['go']['main']['App']['GetCloudElyLinked']();
}

export function GetCloudGameAccounts() {
  return window['go']['main']['App']['GetCloudGameAccounts']();
}

export function GetCloudProfile() {
  return window['go']['main']['App']['GetCloudProfile']();
}

export function GetCreateInstanceLoaderVersions(arg1, arg2) {
  return window['go']['main']['App']['GetCreateInstanceLoaderVersions'](arg1, arg2);
}

export function GetCreateInstanceMinecraftVersions() {
  return window['go']['main']['App']['GetCreateInstanceMinecraftVersions']();
}

export function GetCurrentAccount() {
  return window['go']['main']['App']['GetCurrentAccount']();
}

export function GetCurseForgeKeySettings() {
  return window['go']['main']['App']['GetCurseForgeKeySettings']();
}

export function GetGameAccountInventory(arg1) {
  return window['go']['main']['App']['GetGameAccountInventory'](arg1);
}

export function GetInstanceDetails(arg1) {
  return window['go']['main']['App']['GetInstanceDetails'](arg1);
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function GetLang() {
  return window['go']['main']['App']['GetLang']();
}

export function GetLauncherDebug() {
  return window['go']['main']['App']['GetLauncherDebug']();
}

export function GetLauncherAPITarget() {
  return window['go']['main']['App']['GetLauncherAPITarget']();
}

export function GetLauncherAboutInfo() {
  return window['go']['main']['App']['GetLauncherAboutInfo']();
}

export function GetLauncherVersion() {
  return window['go']['main']['App']['GetLauncherVersion']();
}

export function GetMicrosoftAuthAvailable() {
  return window['go']['main']['App']['GetMicrosoftAuthAvailable']();
}

export function GetNews() {
  return window['go']['main']['App']['GetNews']();
}

export function GetQMServerAPIBase() {
  return window['go']['main']['App']['GetQMServerAPIBase']();
}

export function GetQMServersError() {
  return window['go']['main']['App']['GetQMServersError']();
}

export function InvalidateQMServersCache() {
  return window['go']['main']['App']['InvalidateQMServersCache']();
}

export function GetRecentServers() {
  return window['go']['main']['App']['GetRecentServers']();
}

export function GetSkinProviderConfig() {
  return window['go']['main']['App']['GetSkinProviderConfig']();
}

export function HasCurseForgeAPIKey() {
  return window['go']['main']['App']['HasCurseForgeAPIKey']();
}

export function LaunchInstance(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LaunchInstance'](arg1, arg2, arg3, arg4);
}

export function LaunchInstanceWithAccount(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['LaunchInstanceWithAccount'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function LoginAccount(arg1) {
  return window['go']['main']['App']['LoginAccount'](arg1);
}

export function LogoutAccount() {
  return window['go']['main']['App']['LogoutAccount']();
}

export function LogoutCloudAccount(arg1) {
  return window['go']['main']['App']['LogoutCloudAccount'](arg1);
}

export function OpenBrowserForMicrosoft() {
  return window['go']['main']['App']['OpenBrowserForMicrosoft']();
}

export function OpenBrowserForQMServerCloud() {
  return window['go']['main']['App']['OpenBrowserForQMServerCloud']();
}

export function OpenBrowserURL(arg1) {
  return window['go']['main']['App']['OpenBrowserURL'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function ResolveInstanceResourceStoreLinks(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveInstanceResourceStoreLinks'](arg1, arg2, arg3);
}

export function SearchRemoteStore(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SearchRemoteStore'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetCatalogStoreSettings(arg1, arg2) {
  return window['go']['main']['App']['SetCatalogStoreSettings'](arg1, arg2);
}

export function SetCurseForgeSettingsKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCurseForgeSettingsKey'](arg1, arg2, arg3);
}

export function SetDefaultAccount(arg1) {
  return window['go']['main']['App']['SetDefaultAccount'](arg1);
}

export function SetInstanceMemory(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetInstanceMemory'](arg1, arg2, arg3);
}

export function SetInstanceModEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetInstanceModEnabled'](arg1, arg2, arg3);
}

export function SetInstanceResourceEnabled(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetInstanceResourceEnabled'](arg1, arg2, arg3, arg4);
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function SetLauncherDebug(arg1) {
  return window['go']['main']['App']['SetLauncherDebug'](arg1);
}

export function SetLauncherAPITarget(arg1, arg2) {
  return window['go']['main']['App']['SetLauncherAPITarget'](arg1, arg2);
}

export function SyncLocalAccountToCloud(arg1, arg2) {
  return window['go']['main']['App']['SyncLocalAccountToCloud'](arg1, arg2);
}

export function SyncMicrosoftAccountToCloud() {
  return window['go']['main']['App']['SyncMicrosoftAccountToCloud']();
}

export function Translate(arg1) {
  return window['go']['main']['App']['Translate'](arg1);
}

export function UpdateCloudGameAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCloudGameAccount'](arg1, arg2, arg3);
}
