// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLauncherDbConfig(arg1:number):Promise<main.LauncherDbConfig>;

export function GetMods(arg1:number):Promise<Array<main.ModData>>;

export function GetServers():Promise<Array<main.ServerData>>;

export function GetSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SyncConfigWithServer():Promise<void>;
