// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLauncherDbConfig(arg1) {
  return ObfuscatedCall(33, [arg1]);
}

export function GetMods(arg1) {
  return ObfuscatedCall(34, [arg1]);
}

export function GetServers() {
  return ObfuscatedCall(35, []);
}

export function GetSettings() {
  return ObfuscatedCall(36, []);
}

export function SaveSettings(arg1) {
  return ObfuscatedCall(37, [arg1]);
}

export function SyncConfigWithServer() {
  return ObfuscatedCall(38, []);
}
