// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetJavaPath(arg1) {
  return ObfuscatedCall(31, [arg1]);
}

export function InstallJava(arg1, arg2, arg3) {
  return ObfuscatedCall(32, [arg1, arg2, arg3]);
}

export function ValidateJavaPath(arg1) {
  return ObfuscatedCall(33, [arg1]);
}
