// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function CheckClientInstalled(arg1:number,arg2:string):Promise<main.ClientCheckResult>;

export function InstallMinecraftClient(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.InstallResult>;

export function IsMinecraftRunning():Promise<boolean>;

export function LaunchMinecraft(arg1:main.LaunchMinecraftArgs):Promise<main.LaunchResult>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopMinecraft():Promise<void>;

export function UninstallMinecraft(arg1:number):Promise<main.UninstallResult>;
