// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckClientInstalled(arg1, arg2) {
  return ObfuscatedCall(22, [arg1, arg2]);
}

export function InstallMinecraftClient(arg1, arg2, arg3, arg4) {
  return ObfuscatedCall(23, [arg1, arg2, arg3, arg4]);
}

export function IsMinecraftRunning() {
  return ObfuscatedCall(24, []);
}

export function LaunchMinecraft(arg1) {
  return ObfuscatedCall(25, [arg1]);
}

export function SetContext(arg1) {
  return ObfuscatedCall(26, [arg1]);
}

export function Startup(arg1) {
  return ObfuscatedCall(27, [arg1]);
}

export function StopMinecraft() {
  return ObfuscatedCall(28, []);
}

export function UninstallMinecraft(arg1) {
  return ObfuscatedCall(29, [arg1]);
}
